'use strict';
const REPORT_UPDATE_CSS=`
.report-pages{font-family:Arial,Tajawal,sans-serif}.report-pages *{letter-spacing:normal!important;word-break:normal!important;hyphens:none}.school-report .student-name{line-height:1.5;overflow-wrap:normal!important}.plan-grid{display:grid;grid-template-columns:1fr 1fr;gap:6px 12px}.plan-grid .plan-item{margin:0}.aggregate-note{font-size:12px;line-height:1.8}.aggregate-stats{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px;margin:16px 0}.aggregate-stats>div{border:1px solid #dce5e0;border-radius:8px;padding:12px;text-align:center}.aggregate-stats strong{display:block;font-size:24px}.aggregate-stats span{font-size:12px}.aggregate-bars{display:grid;gap:12px}.aggregate-bar-label{display:flex;justify-content:space-between;gap:12px;font-size:13px}.aggregate-track{height:12px;background:#e9efec;border:1px solid #a6bbb3;border-radius:3px;margin-top:4px;overflow:hidden}.aggregate-track span{display:block;height:100%;background:#087f80;print-color-adjust:exact;-webkit-print-color-adjust:exact}.aggregate-bar{break-inside:avoid}.aggregate-list td:first-child{font-weight:bold}.aggregate-list th,.aggregate-list td{padding:8px!important}.school-report.aggregate-report h2{font-size:20px}.aggregate-progress{padding:12px;border:1px solid #dce5e0;border-radius:8px;margin-top:16px}.aggregate-progress p{margin:4px 0}.aggregate-report .student-name{font-size:13px!important}.aggregate-report .aggregate-section{margin-top:18px}.aggregate-report tbody tr{break-inside:avoid}.aggregate-report thead{display:table-header-group}
@media screen and (max-width:600px){.plan-grid{grid-template-columns:1fr}.aggregate-stats{grid-template-columns:1fr 1fr}.aggregate-list th,.aggregate-list td{font-size:10px!important;padding:5px!important}}
@media print{.report-pages{font-size:10pt;line-height:1.45}.school-report{page-break-after:always}.school-report:last-child{page-break-after:auto}.report-letterhead{padding-bottom:7px;gap:10px;break-inside:avoid}.report-letterhead h1{font-size:16pt;margin:4px 0}.report-letterhead p{font-size:8pt;line-height:1.5;margin:2px 0}.report-letterhead img{width:55px;height:55px}.report-student{margin:10px 0;padding:9px 12px}.school-report .student-name{font-size:15pt;margin:2px 0 5px;line-height:1.5}.student-meta{font-size:9pt;gap:5px 14px}.report-stats>div{padding:6px}.report-stats strong{font-size:17pt}.report-section{margin-top:12px}.report-section h3{font-size:12pt;margin:0 0 6px}.school-report td,.school-report th{font-size:9pt;padding:5px;line-height:1.5}.plan-duration{font-size:8.5pt;margin:5px 0 8px}.plan-grid{grid-template-columns:1fr 1fr;gap:6px 10px}.plan-item{padding:6px 8px}.plan-item strong{font-size:9.5pt}.plan-item p{font-size:9pt;line-height:1.5;margin:2px 0}.report-signature{margin-top:10px;padding-top:6px;font-size:9pt}.aggregate-stats{margin:12px 0;gap:8px}.aggregate-stats>div{padding:8px}.aggregate-stats strong{font-size:17pt}.aggregate-stats span,.aggregate-note{font-size:9pt}.aggregate-bar-label{font-size:10pt}.aggregate-bars{gap:8px}.aggregate-progress{break-inside:avoid}.aggregate-section h2{break-after:avoid}.aggregate-list td,.aggregate-list th{font-size:9pt!important}.aggregate-report .student-name{font-size:10pt!important}.aggregate-report{break-after:auto!important;page-break-after:auto!important}}
`;
function reportDate(value){const d=new Date(value);if(!Number.isFinite(+d))return '';return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Riyadh',year:'numeric',month:'2-digit',day:'2-digit'}).format(d);}
function reportExtraMatch(r,f){const date=reportDate(r.result.submittedAt);return (!(f.from&&f.to&&f.from>f.to))&&(!f.from||date>=f.from)&&(!f.to||date<=f.to)&&(!f.studentIds?.length||f.studentIds.includes(String(r.studentId)))&&!String(r.result.examId).startsWith('DEMO-');}
function reportExtraFilters(){
 const filters=$('.filters');if(!filters||$('#report-from'))return;
 const extra=document.createElement('div');extra.className='report-extra-filters';extra.style.gridColumn='1 / -1';
 extra.innerHTML='<div class="actions"><div class="field"><label for="report-from">من تاريخ</label><input type="date" id="report-from"></div><div class="field"><label for="report-to">إلى تاريخ</label><input type="date" id="report-to"></div></div><details><summary>تحديد مجموعة طلاب (اختياري)</summary><p class="hint">دون تحديد أسماء يشمل التقرير جميع الطلاب المطابقين للفلاتر.</p><div class="student-select-list">'+[...new Map(report.map(r=>[r.studentId,r])).values()].sort((a,b)=>a.name.localeCompare(b.name,'ar')).map(r=>'<label><input type="checkbox" data-report-student value="'+esc(r.studentId)+'"><span>'+esc(r.name)+' · '+esc(r.classroom)+'</span></label>').join('')+'</div></details><p class="error" id="report-filter-error" role="alert"></p>';
 filters.append(extra);extra.querySelectorAll('input').forEach(i=>i.onchange=drawReport);
}
function aggregateData(rows,f){
 const {filtered,groups}=collectReport(rows,f),students=new Map(),skills=new Map();
 for(const g of groups){const s=students.get(g.studentId)||{studentId:g.studentId,name:g.name,classroom:g.classroom,total:0,correct:0,unanswered:0};for(const key of ['total','correct','unanswered'])s[key]+=g[key];students.set(g.studentId,s);const k=skills.get(g.skillId)||{skillId:g.skillId,skill:g.skill,total:0,correct:0,unanswered:0};for(const key of ['total','correct','unanswered'])k[key]+=g[key];skills.set(g.skillId,k);}
 const allStudents=[...students.values()],mean=allStudents.length?allStudents.reduce((n,s)=>n+s.correct/s.total*100,0)/allStudents.length:null;
 const comparisons=new Map();
 for(const r of filtered){if(r.result.version==null)continue;const qs=r.result.review.filter(q=>!f.skillId||q.skillId===f.skillId);if(!qs.length)continue;const key=JSON.stringify([r.studentId,r.result.examId,r.result.version]),item={studentId:r.studentId,score:qs.filter(q=>q.isCorrect).length/qs.length*100,attemptId:r.result.attemptId,shape:qs.map(q=>q.questionId).sort().join('|')};const pair=comparisons.get(key);if(!pair)comparisons.set(key,{first:item,last:item});else pair.last=item;}
 const changes=new Map();let comparedTests=0;
 for(const {first,last} of comparisons.values()){if(first.attemptId===last.attemptId||first.shape!==last.shape)continue;const a=changes.get(first.studentId)||[];a.push(last.score-first.score);changes.set(first.studentId,a);comparedTests++;}
 const deltas=[...changes.values()].map(v=>v.reduce((a,b)=>a+b,0)/v.length);
 const total=groups.reduce((n,g)=>n+g.total,0),correct=groups.reduce((n,g)=>n+g.correct,0),unanswered=groups.reduce((n,g)=>n+g.unanswered,0);
 return {participants:new Set(filtered.map(r=>r.studentId)).size,attempts:filtered.length,exams:new Set(filtered.map(r=>r.result.examId)).size,students:allStudents,skills:[...skills.values()],mean,total,correct,unanswered,wrong:total-correct-unanswered,progressCount:changes.size,comparedTests,delta:deltas.length?deltas.reduce((a,b)=>a+b,0)/deltas.length:null};
}
function aggregateHeader(){return '<header class="report-letterhead"><img src="'+new URL('assets/moe.svg',document.baseURI).href+'" alt="شعار وزارة التعليم"><div><p>المملكة العربية السعودية · وزارة التعليم<br>الإدارة العامة للتعليم بالقصيم<br>مدرسة الإمام الشوكاني الابتدائية بالمذنب</p><h1>التقرير الإجمالي لأداء الطلاب</h1><p>محاكي نافس المطور · النسخة الثانية</p></div><img src="'+new URL('assets/school.webp',document.baseURI).href+'" alt="شعار المدرسة"></header>';}
function aggregateBar(label,value,total){const percent=total?value/total*100:0;return '<div class="aggregate-bar"><div class="aggregate-bar-label"><span>'+esc(label)+'</span><strong>'+ar(value)+' / '+ar(total)+' · '+ar(Math.round(percent))+'٪</strong></div><div class="aggregate-track"><span style="width:'+percent+'%"></span></div></div>';}
function aggregateMarkup(rows,f){
 const d=aggregateData(rows,f),scope=[f.classroom||'جميع الفصول',C.exams.find(e=>e.id===f.examId)?.title||'جميع الاختبارات',f.skillId?C.skills.find(s=>s.id===f.skillId)?.label:'جميع المهارات',f.studentId?'طالب محدد':f.studentIds?.length?'مجموعة مختارة':'جميع الطلاب المطابقين',f.name?'البحث: '+f.name:'',f.from?'من '+f.from:'',f.to?'إلى '+f.to:''].filter(Boolean).join(' · ');
 const stat=(v,t)=>'<div><strong>'+v+'</strong><span>'+t+'</span></div>';
 return '<div class="report-pages"><section class="school-report aggregate-report">'+aggregateHeader()+'<p class="aggregate-note">'+esc(scope)+'<br>تاريخ التقرير: '+esc(new Date().toLocaleDateString('ar-SA'))+'</p><div class="aggregate-stats">'+stat(ar(d.participants),'عدد الطلاب الذين أكملوا اختبارًا واحدًا على الأقل')+stat(ar(d.attempts),'المحاولات المسلمة')+stat(ar(d.exams),'الاختبارات المختلفة المكتملة')+stat(d.mean===null?'—':ar(Math.round(d.mean))+'٪','متوسط نسب الطلاب')+stat(ar(d.total),'الأسئلة المحتسبة في المهارات')+stat(ar(d.students.length),'طلاب تتوفر لهم بيانات المهارات المختارة')+'</div><p class="aggregate-note">يُحتسب كل طالب مرة واحدة. ملخص المهارات والإجابات يعتمد أول إجابة مسلمة لكل سؤال وإصدار ضمن الفترة المختارة، مثل التقارير الفردية. المتوسط هو متوسط نسب الطلاب، وليس متوسط المحاولات المتكررة.</p>'+(!d.participants?'<p>لا توجد نتائج ضمن هذا الاختيار.</p>':'')+'<section class="aggregate-section"><h2>أداء الطلاب بحسب المهارة</h2><div class="aggregate-bars">'+d.skills.map(s=>aggregateBar(s.skill,s.correct,s.total)).join('')+'</div></section><section class="aggregate-section"><h2>توزيع الإجابات</h2><div class="aggregate-bars">'+[['صحيحة',d.correct],['خاطئة',d.wrong],['متروكة',d.unanswered]].map(([l,n])=>aggregateBar(l,n,d.total)).join('')+'</div></section><section class="aggregate-progress"><h2>التقدم بين المحاولات</h2><p>'+(d.delta===null?'لا تتوفر محاولات كافية لقياس التقدم':(d.delta>0?'تحسن بمتوسط ':d.delta<0?'انخفاض بمتوسط ':'ثبات بمتوسط ')+ar(Math.round(Math.abs(d.delta)*10)/10)+' نقطة مئوية · '+ar(d.progressCount)+' طلاب · '+ar(d.comparedTests)+' مقارنات لاختبار وإصدار متماثلين')+'</p><p class="aggregate-note">تُقارن المحاولة الأولى بالأحدث للاختبار والإصدار والأسئلة نفسها داخل الفترة المختارة. يُحسب متوسط تغير كل طالب أولًا ثم متوسط الطلاب الذين تتوفر لهم مقارنة.</p></section>'+(f.includeNames===false?'':'<section class="aggregate-section"><h2>ملخص الطلاب</h2><table class="aggregate-list"><colgroup><col style="width:34%"><col style="width:18%"><col span="4" style="width:12%"></colgroup><thead><tr><th>الطالب</th><th>الفصل</th><th>صحيح</th><th>خطأ</th><th>متروك</th><th>النسبة</th></tr></thead><tbody>'+d.students.map(s=>'<tr><td><span class="student-name">'+esc(s.name)+'</span><br><bdi dir="ltr">'+esc(s.studentId)+'</bdi></td><td>'+esc(s.classroom)+'</td><td>'+ar(s.correct)+'</td><td>'+ar(s.total-s.correct-s.unanswered)+'</td><td>'+ar(s.unanswered)+'</td><td>'+ar(Math.round(s.correct/s.total*100))+'٪</td></tr>').join('')+'</tbody></table></section>')+'<div class="report-signature">إعداد الأستاذ مقرن المطيري</div></section></div>';
}
function aggregateTools(){
 const s=document.createElement('section');s.className='report-tools';s.innerHTML='<h2>التقرير الإجمالي</h2><label class="report-option"><input id="aggregate-names" type="checkbox" checked> تضمين جدول أسماء الطلاب</label><div class="actions">'+btn(icon('print')+'طباعة التقرير الإجمالي / حفظ PDF','id="print-aggregate"')+btn(icon('download')+'تنزيل التقرير الإجمالي','id="download-aggregate"','light')+'</div>';
 $('#report-body').prepend(s);$('#print-aggregate').onclick=()=>outputAggregate('print');$('#download-aggregate').onclick=()=>outputAggregate('download');
}
async function outputAggregate(kind){
 if(!teacherSession)return;const f={...reportSelection(),includeNames:$('#aggregate-names').checked};if(f.from&&f.to&&f.from>f.to){notify('تاريخ البداية يجب أن يسبق النهاية.');return;}
 const session=teacherSession,markup=aggregateMarkup(report,f);if(kind==='print'){await printReportMarkup(markup);return;}
 const button=$('#download-aggregate');button.disabled=true;
 try{let html='<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>التقرير الإجمالي</title><style>'+REPORT_CSS+'</style></head><body>'+markup+'</body></html>';html=await embedReportLogos(html);if(session!==teacherSession)return;const url=URL.createObjectURL(new Blob([html],{type:'text/html;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='Nafis-Summary-'+new Date().toISOString().slice(0,10)+'.html';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);}catch{notify('تعذر تنزيل التقرير. أعد المحاولة.');}finally{if(button.isConnected)button.disabled=false;}
}
async function printReportMarkup(markup){
 const session=teacherSession;$('#print-report-root')?.remove();const root=document.createElement('div');root.id='print-report-root';root.innerHTML='<style>'+REPORT_CSS+'</style>'+markup;document.body.append(root);
 try{await Promise.all([...root.querySelectorAll('img')].map(img=>img.decode()));if(session!==teacherSession){root.remove();return;}await document.fonts?.ready;document.body.classList.add('printing-report');window.print();}catch{document.body.classList.remove('printing-report');root.remove();notify('تعذر تحميل التقرير. أعد المحاولة.');}
}
